package Day4;


import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;

public class Main {
    public static String getMd5(String input)
    {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());

            BigInteger no = new BigInteger(1, messageDigest);

            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }

        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }



    public static void main(String[] args) throws NoSuchAlgorithmException {

        String input = "iwrupvqb";
        System.out.println("Your key: " + input);
        int number = 0;
        String password = "";

        while (!getMd5(password).startsWith("000000")){
            number++;
            password = input + number;
        }

        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(password));
        System.out.println("Number used: " + number);

    }
}
